### ISSUE TITLE
After SSL certificate website get loop loading

### ISSUE THREAD

**Issue by ghost** [znixhook/panel#10]
Hello.
After installing the SSL certificate, the website does not want to be fully loaded. It looks like "loop load" or something like that
How to fix it ??????

// edit: Yes i tried to remove browser history.
![20200906_235841.jpg](https://user-images.githubusercontent.com/68196622/92336156-da3a3180-f09d-11ea-82d4-981674b84e9f.jpg)

**Comment by znixbtw** [comment]
ive seen this problem happen to multiple people, though it works fine on my server(with SSL) easiest fix is to completely remove the animation....

**Comment by ghost** [comment]
Oh ok thanks for help!
