### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by qalxlslml1** [znixhook/panel#4]
I installed the panel on the host, connected the database, I go to the site and there is always loading

**Comment by qalxlslml1** [comment]
and in db you have 2 error 
  `time` datetime(6) NOT NULL DEFAULT current_timestamp(6),
this and
  `created_at` datetime DEFAULT current_timestamp(),
function current_timestamp() is only for timestamp and function current_timestamp(6) change datetime to timestamp and  current_timestamp(6) to current_timestamp()

**Comment by znixbtw** [comment]
Endless loading seems like your problem. No one else had a similar problem.

**Comment by qalxlslml1** [comment]
I don’t know I have all the scripts working stably + the host is not a free problem only with this script

**Comment by qalxlslml1** [comment]
I removed the loading animation and everything works, it's something with animation

**Comment by qalxlslml1** [comment]
and please create api tutorial

**Comment by caiocinel** [comment]
> and please create api tutorial

You have the SOURCE CODE of the API, it is much easier for you to interpret it.
