### ISSUE TITLE
Possible XSS

### ISSUE THREAD

**Issue by BurstInject0r** [znixhook/panel#5]
I found multiple possibles XSS vulnerabilities.

**Login.php**
If you put `"><script>alert(1);</script>` in the username parameter you can execute scripts.

**Register.php**
If you put `"><script>alert(1);</script>` in the password AND/OR confirm_password parameter you can execute scripts.

Im not sure how dangerous they are in that case, but you could fix them.

**Comment by znixbtw** [comment]
fixed.

**Comment by znixbtw** [comment]
I don't see any other XSS bugs.
Not closing this thread in case you have something to say.

**Comment by znixbtw** [comment]
Looks like there is nothing to say.
