### ISSUE TITLE
shoutbox dont work

### ISSUE THREAD

**Issue by Diwiasln** [znixhook/panel#7]
get_msgs.php work but in index.php shuotbox always clear

**Comment by znixbtw** [comment]
Provide more info?
It works perfectly fine for me.

**Comment by Diwiasln** [comment]
mainpage
![image](https://user-images.githubusercontent.com/59170754/90318794-a86cf980-df3b-11ea-83b5-9518e52fa532.png)

get_msgs.php output
![image](https://user-images.githubusercontent.com/59170754/90318788-99864700-df3b-11ea-8f08-7b06c7494d93.png)

index.php code i chance only config and db connect
![image](https://user-images.githubusercontent.com/59170754/90318868-1f09f700-df3c-11ea-8886-15d228a3ad03.png)



and shoutbox id is result
![image](https://user-images.githubusercontent.com/59170754/90318857-08fc3680-df3c-11ea-8ac2-4dae99a418e8.png)

**Comment by znixbtw** [comment]
Try on a different server.
Pretty sure ajax is not working properly for you.
![](https://codeine.is-inside.me/62fCDmzi.gif)
